### PR TITLE
feat: adds litestar to web frameworks

### PR DESCRIPTION
**Pull request by cofin**
This PR adds Litestar into the web framework section.

### CODE REVIEW

**Comment by cofin** [comment]
Also, I don't see the existing Litestar entry on `https://pythonframeworks.com/`. 

Perhaps you need to do a new deployment?

**Comment by jgujerry** [comment]
Hi @cofin Thanks for PR.

I was thinking Litestar focuses more on API development, so just put it into `API` section, as sometimes it's hard to category web and api frameworks. I think you are right, it could be part of `Web` section as well, as the Templating of Litestar is great for building web apps.

Further discussion, it'd be better if the description of Litestar on `Web` section could be updated, so that to highlight its features on web application (non-api) development, currently it's highlighting the API development, any thought?

**Comment by cofin** [comment]
> Hi @cofin Thanks for PR.
> 
> I was thinking Litestar focuses more on API development, so just put it into `API` section, as sometimes it's hard to category web and api frameworks. I think you are right, it could be part of `Web` section as well, as the Templating of Litestar is great for building web apps.
> 
> Further discussion, it'd be better if the description of Litestar on `Web` section could be updated, so that to highlight its features on web application (non-api) development, currently it's highlighting the API development, any thought?

I didn't modify the text because It looks like most of these entries are just the taglines from their respective websites, but I agree that it could be more descriptive (this goes for many of the other entries as well though)

Re: the inclusion in Web or only API lists, Litestar is a full-featured framework that can be used for either, and given the entries already in these sections, it should be included in both.

Let me know what you'd like to be done to get this merged.

**Comment by jgujerry** [comment]
> Let me know what you'd like to be done to get this merged.

Makes sense, let's update the description of Litestar in the `Web` section, then get it merged.

In its documentation https://docs.litestar.dev/2/, it says:
```
Litestar is a powerful, flexible, highly performant, and opinionated ASGI framework.
```
It looks good to me as a comprehensive description for web development. If agreed, you may place it as description of Litestar in Web section, then we can merge the PR.

**Comment by jgujerry** [comment]
@cofin Please feel free to change the style of the card as well if like, such as the title, tagline/description, font, font-size, color, and so on.

**Comment by cofin** [comment]
@jgujerry thanks!  I'll be sure to update this once I'm back in town from holiday travel.

**Comment by jgujerry** [comment]
No activity on this PR. I'll simply merge and update the tagline for adding Litestar into Web section, as Litestar is a full-featured web framework.

**Review by jgujerry — APPROVED** [review]

**Pull request merged**
