### PR TITLE
Added Flet UI Framework

### PR DESCRIPTION
**Pull request by nasoma**
Added Flet (https://github.com/flet-dev/flet), a new framework to build web, mobile, and desktop apps.

### CODE REVIEW

**Review by jgujerry — COMMENTED** [review]
Awesome! Thanks for the PR and adding Flex.

There are some extra work before we merge it, could you help
* To add `.DS_Store` into `.gitignore` and remove the MacOS file from your commit.
* To append another card to `Web Apps` category, as Flex support web development as well. 

Best

**Comment by nasoma** [comment]
1. Added `.DS_Store` into `.gitignore`.
2. Appended new card for Flet in the `Web Apps` category.

**Comment by jgujerry** [comment]
Hi @nasoma Thanks for the update.

It looks the `static/.DS_Store` is still in the commit, try `git rm --cached static/.DS_Store` to remove it from your local staging area.

Thank you!

**Comment by nasoma** [comment]
All instances of .DS_Store have been removed.

**Review by jgujerry — APPROVED** [review]

**Pull request merged**
