### PR TITLE
Adding Zato to the list.

### PR DESCRIPTION
**Pull request by dsuch**
Hi @jgu-bytes,

I have just added [Zato](https://zato.io) to the list as well.

Regards.

### CODE REVIEW

**Comment by jgujerry** [comment]
Hi @dsuch, thanks for the PR. It's a great chance for me to learn zato, it's really a great open-source project in Python.

As you said, zato covers many aspects listed on https://pythonframeworks.com. However, it's not traditionally like other frameworks/libraries in category. I believe it's worth a new category.

How about this, putting just above `GUI & TUI` category:
```html

    <!--Appication Integration-->
    <h3 class="mt-4 display-6">Application Integration</h3>
    <p>
      In the realm of enterprise service bus (ESB) and application integration, Python serves as a powerful and versatile ally.
      With framework like Zato, developers can seamlessly orchestrate the interconnection of disparate systems,
      enabling efficient communication and collaboration between applications.
    </p>

    <div class="row grids mt-4" data-masonry='{"percentPosition": true }'>

      <div class="col-12 col-sm-6 col-lg-3 mb-4">
        <div class="card text-end">
          <a class="text-center m-3" href="https://zato.io" target="_blank">
            <img class="card-img-top" src="static/image/logos/zato.svg" style="width:70%;height:auto" alt="Zato home page">
          </a>
          <hr class="my-2">
          <div class="card-body text-center">
            <h3 class="card-title"><a href="https://zato.io" target="_blank">Zato</a></h3>
            <p class="card-text">Open-source Enterprise Service Bus, API, AI and Cloud Integrations in Python.</p>
            <h6 class="card-text"> - <i>Integrate everything. In Python.</i></h6>
          </div>
        </div>
      </div>

    </div>
    <!--End of Application Integration-->
```

And, the page would like this
image

Would it work for zato? If this format work, would you mind update the PR? also please feel to update the category name and description that I drafted, and make it more accurate for work in this area.

**Comment by dsuch** [comment]
Hi @jgu-bytes,

yes, I like this idea and I have just committed the changes to my repository and they are in this PR now.

I would still keep Zato in the other categories because a significant part of what is does is enabling one to create backend, API-only systems that, for instance, offer REST or WebSocket-based APIs to web or mobile apps, which is similar to integrations but integrations are usually stateless whereas here we have a stateful backend system that is API-only.

It also has its own [publish/subscribe](https://zato.io/en/docs/3.2/pubsub/index.html) topics and message queues, and similar capabilities that make it a good fit for more than one category.

Regards.

**Comment by jgujerry** [comment]
Hi @dsuch,

Thanks for the update and thoughtful suggestion to add zato into more categories. I appreciate your engagement and interest in improving this web page. After careful consideration, I believe putting zato under 'Application Integrations' would align closely with its primary functionality and purpose. My vision of this site is aimed to providing a focused and clear representation of each framework strength, though there's a few frameworks located into 2 categories (For example, FastAPI could build web pages with template, or just APIs), most of each is within one category. And, I plan to change the description in duplicated cards in the near future.

If there are specific aspects you feel are not adequately covered by "Application Integrations", I'd happy to discuss alternative approach, for example, **we could update the descriptions in zato's card, providing it's capabilities in Web, API, and Task Queue development, etc**. However, if there's third party plugin/lib in zato's ecosystem, something like "Django Rest Framework" to Django, "APIFlask" to Flask framework, then it's great to add them into different categories.

Your insights is valuable, I am open to ongoing discussions and would happy to feature out the way to organize for zato, so to keep it's strength and uniqueness in Python ecosystem.

Best

**Comment by dsuch** [comment]
Hi @jgu-bytes,

I see your point, this is clear.

My intention was to express the fact that Zato has, as an example, message queues built in, i.e. it is an integral part of it, there is no need for any plug-ins because it is already included. That is why it fits into more than one category.

Compare it with, say, Ubuntu, where most people use it as a server but it is a desktop system too, which means it would go to two categories in a list similar to yours.

But I also like the idea of adding a specific category for this kind of solutions and it is a good idea to have a different description if a given tool matches more than one category, that is a good point.

Hence, I would suggest:

- I have moved Zato to Application Integrations only for now
- You can merge the PR at this point
- Later on, I will come up with different descriptions for its other roles, e.g. if it can be used as a message queue, then it will speak about that specifically. I will do it for APIs, message queues and workflows because these are very much use cases that Zato is used in.
- Once I have the new descriptions, I will open a new PR and we can simply return to the discussion

What do you think about it?

**Comment by jgujerry** [comment]
> Hi @jgu-bytes,
> 
> I see your point, this is clear.
> 
> My intention was to express the fact that Zato has, as an example, message queues built in, i.e. it is an integral part of it, there is no need for any plug-ins because it is already included. That is why it fits into more than one category.
> 
> Compare it with, say, Ubuntu, where most people use it as a server but it is a desktop system too, which means it would go to two categories in a list similar to yours.
> 
> But I also like the idea of adding a specific category for this kind of solutions and it is a good idea to have a different description if a given tool matches more than one category, that is a good point.
> 
> Hence, I would suggest:
> 
> * I have moved Zato to Application Integrations only for now
> * You can merge the PR at this point
> * Later on, I will come up with different descriptions for its other roles, e.g. if it can be used as a message queue, then it will speak about that specifically. I will do it for APIs, message queues and workflows because these are very much use cases that Zato is used in.
> * Once I have the new descriptions, I will open a new PR and we can simply return to the discussion
> 
> What do you think about it?

It sounds a good plan, I'll be happy to hear more from zato, thank you!

**Review by jgujerry — APPROVED** [review]

**Pull request merged**
